### ISSUE TITLE
Running ESLint config setup failing with `NMAKE : fatal error U1052: file 'Makefile.msvc' not found`

### ISSUE THREAD

**Issue by Draikth** [upleveled/eslint-config-upleveled#414]
:one: What happened that was unexpected

I followed the ESLint setup from the readme this repo,  and I ended up with a strange error and the dependency won't install... Error from Hyper and screenshot of package.json comparisons to follow...
```
Detected project type: Next.js with PostgreSQL
Installing 4 ESLint config dependencies...
 WARN  8 deprecated subdependencies found: @humanwhocodes/config-array@0.13.0, @humanwhocodes/object-schema@2.0.3, are-we-there-yet@2.0.0, gauge@3.0.2, glob@7.2.3, inflight@1.0.6, npmlog@5.0.1, rimraf@3.0.2
Packages: +117
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 669, reused 620, downloaded 0, added 1, done
node_modules/.pnpm/libpg-query@15.2.0_encoding@0.1.13/node_modules/libpg-query: Running install script, failed in 9s
.../node_modules/libpg-query install$ node-pre-gyp install --fallback-to-build --loglevel verbose
│ node-pre-gyp info it worked if it ends with ok
│ node-pre-gyp verb cli [
│ node-pre-gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
│ node-pre-gyp verb cli   'C:\\Users\\User\\projects\\nextjs-ecomm-store\\node_modules\\.pnpm\\@mapbox+node-pre-gyp@1.0.11_encoding@0.1.13\\node_modules\\@mapbox\\node-pre-…  
│ node-pre-gyp verb cli   'install',
│ node-pre-gyp verb cli   '--fallback-to-build',
│ node-pre-gyp verb cli   '--loglevel',
│ node-pre-gyp verb cli   'verbose'
│ node-pre-gyp verb cli ]
│ node-pre-gyp info using node-pre-gyp@1.0.11
│ node-pre-gyp info using node@20.12.1 | win32 | x64
│ node-pre-gyp verb command install []
│ node-pre-gyp info check checked for "C:\Users\User\projects\nextjs-ecomm-store\node_modules\.pnpm\libpg-query@15.2.0_encoding@0.1.13\node_modules\libpg-query\build\Releas…  
│ node-pre-gyp http GET https://supabase-public-artifacts-bucket.s3.amazonaws.com/libpg-query-node/queryparser-v15.2.0-node-v115-win32-x64.tar.gz
│ node-pre-gyp ERR! install response status 404 Not Found on https://supabase-public-artifacts-bucket.s3.amazonaws.com/libpg-query-node/queryparser-v15.2.0-node-v115-win32-…  
│ node-pre-gyp WARN Pre-built binaries not installable for libpg-query@15.2.0 and node@20.12.1 (node-v115 ABI, unknown) (falling back to source compile with node-gyp)
│ node-pre-gyp WARN Hit error response status 404 Not Found on https://supabase-public-artifacts-bucket.s3.amazonaws.com/libpg-query-node/queryparser-v15.2.0-node-v115-win3…  
│ node-pre-gyp verb command build [ 'rebuild' ]
│ gyp info it worked if it ends with ok
│ gyp info using node-gyp@10.1.0
│ gyp info using node@20.12.1 | win32 | x64
│ gyp info ok
│ gyp info it worked if it ends with ok
│ gyp verb cli [
│ gyp verb cli 'C:\\Program Files\\nodejs\\node.exe',
│ gyp verb cli 'C:\\Users\\User\\AppData\\Local\\node\\corepack\\v1\\pnpm\\9.3.0\\dist\\node_modules\\node-gyp\\bin\\node-gyp.js',
│ gyp verb cli 'configure',
│ gyp verb cli '--fallback-to-build',
│ gyp verb cli '--loglevel=verbose',
│ gyp verb cli '--module=C:\\Users\\User\\projects\\nextjs-ecomm-store\\node_modules\\.pnpm\\libpg-query@15.2.0_encoding@0.1.13\\node_modules\\libpg-query\\build\\Release\\…  
│ gyp verb cli '--module_name=queryparser',
│ gyp verb cli '--module_path=C:\\Users\\User\\projects\\nextjs-ecomm-store\\node_modules\\.pnpm\\libpg-query@15.2.0_encoding@0.1.13\\node_modules\\libpg-query\\build\\Rele…  
│ gyp verb cli '--napi_version=9',
│ gyp verb cli '--node_abi_napi=napi',
│ gyp verb cli '--napi_build_version=0',
│ gyp verb cli '--node_napi_label=node-v115'
│ gyp verb cli ]
│ gyp info using node-gyp@10.1.0
│ gyp info using node@20.12.1 | win32 | x64
│ gyp verb find Python Python is not set from command line or npm configuration
│ gyp verb find Python Python is not set from environment variable PYTHON
│ gyp verb find Python checking if the py launcher can be used to find Python 3
│ gyp verb find Python - executing "py.exe" to get Python 3 executable path
│ gyp verb find Python - executable path is "C:\Python312\python.exe"
│ gyp verb find Python - executing "C:\Python312\python.exe" to get version
│ gyp verb find Python - version is "3.12.2"
│ gyp info find Python using Python version 3.12.2 found at "C:\Python312\python.exe"
│ gyp verb get node dir no --target version specified, falling back to host node version: 20.12.1
│ gyp verb install input version string "20.12.1"
│ gyp verb install installing version: 20.12.1
│ gyp verb install --ensure was passed, so won't reinstall if already installed
│ gyp verb install version is already installed, need to check "installVersion"
│ gyp verb got "installVersion" 11
│ gyp verb needs "installVersion" 11
│ gyp verb install version is good
│ gyp verb on Windows; need to check node.lib
│ gyp verb get node dir target node version installed: 20.12.1
│ gyp verb build dir attempting to create "build" dir: C:\Users\User\projects\nextjs-ecomm-store\node_modules\.pnpm\libpg-query@15.2.0_encoding@0.1.13\node_modules\libpg-qu…  
│ gyp verb build dir "build" dir needed to be created? Yes
│ gyp verb find VS msvs_version not set from command line or npm config
│ gyp verb find VS VCINSTALLDIR not set, not running in VS Command Prompt
│ gyp verb find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details.
│ gyp verb find VS
│ gyp verb find VS Failure details: undefined
│ gyp verb find VS checking VS2022 (17.9.34723.18) found at:
│ gyp verb find VS "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools"
│ gyp verb find VS - found "Visual Studio C++ core features"
│ gyp verb find VS - found VC++ toolset: v143
│ gyp verb find VS - found Windows SDK: 10.0.22621.0
│ gyp info find VS using VS2022 (17.9.34723.18) found at:
│ gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools"
│ gyp info find VS run with --verbose for detailed information
│ gyp verb build/config.gypi creating config file
│ gyp verb build/config.gypi writing out config file: C:\Users\User\projects\nextjs-ecomm-store\node_modules\.pnpm\libpg-query@15.2.0_encoding@0.1.13\node_modules\libpg-que…  
│ gyp verb config.gypi checking for gypi file: C:\Users\User\projects\nextjs-ecomm-store\node_modules\.pnpm\libpg-query@15.2.0_encoding@0.1.13\node_modules\libpg-query\conf…  
│ gyp verb common.gypi checking for gypi file: C:\Users\User\projects\nextjs-ecomm-store\node_modules\.pnpm\libpg-query@15.2.0_encoding@0.1.13\node_modules\libpg-query\comm…  
│ gyp verb gyp gyp format was not specified; forcing "msvs"
│ gyp info spawn C:\Python312\python.exe
│ gyp info spawn args [
│ gyp info spawn args 'C:\\Users\\User\\AppData\\Local\\node\\corepack\\v1\\pnpm\\9.3.0\\dist\\node_modules\\node-gyp\\gyp\\gyp_main.py',
│ gyp info spawn args 'binding.gyp',
│ gyp info spawn args '-f',
│ gyp info spawn args 'msvs',
│ gyp info spawn args '-I',
│ gyp info spawn args 'C:\\Users\\User\\projects\\nextjs-ecomm-store\\node_modules\\.pnpm\\libpg-query@15.2.0_encoding@0.1.13\\node_modules\\libpg-query\\build\\config.gypi…  
│ gyp info spawn args '-I',
│ gyp info spawn args 'C:\\Users\\User\\AppData\\Local\\node\\corepack\\v1\\pnpm\\9.3.0\\dist\\node_modules\\node-gyp\\addon.gypi',
│ gyp info spawn args '-I',
│ gyp info spawn args 'C:\\Users\\User\\AppData\\Local\\node-gyp\\Cache\\20.12.1\\include\\node\\common.gypi',
│ gyp info spawn args '-Dlibrary=shared_library',
│ gyp info spawn args '-Dvisibility=default',
│ gyp info spawn args '-Dnode_root_dir=C:\\Users\\User\\AppData\\Local\\node-gyp\\Cache\\20.12.1',
│ gyp info spawn args '-Dnode_gyp_dir=C:\\Users\\User\\AppData\\Local\\node\\corepack\\v1\\pnpm\\9.3.0\\dist\\node_modules\\node-gyp',
│ gyp info spawn args '-Dnode_lib_file=C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\20.12.1\\\\<(target_arch)\\\\node.lib',
│ gyp info spawn args '-Dmodule_root_dir=C:\\Users\\User\\projects\\nextjs-ecomm-store\\node_modules\\.pnpm\\libpg-query@15.2.0_encoding@0.1.13\\node_modules\\libpg-query',   
│ gyp info spawn args '-Dnode_engine=v8',
│ gyp info spawn args '--depth=.',
│ gyp info spawn args '--no-parallel',
│ gyp info spawn args '--generator-output',
│ gyp info spawn args 'C:\\Users\\User\\projects\\nextjs-ecomm-store\\node_modules\\.pnpm\\libpg-query@15.2.0_encoding@0.1.13\\node_modules\\libpg-query\\build',
│ gyp info spawn args '-Goutput_dir=.'
│ gyp info spawn args ]
│ gyp info ok
│ gyp info it worked if it ends with ok
│ gyp verb cli [
│ gyp verb cli 'C:\\Program Files\\nodejs\\node.exe',
│ gyp verb cli 'C:\\Users\\User\\AppData\\Local\\node\\corepack\\v1\\pnpm\\9.3.0\\dist\\node_modules\\node-gyp\\bin\\node-gyp.js',
│ gyp verb cli 'build',
│ gyp verb cli '--fallback-to-build',
│ gyp verb cli '--loglevel=verbose',
│ gyp verb cli '--module=C:\\Users\\User\\projects\\nextjs-ecomm-store\\node_modules\\.pnpm\\libpg-query@15.2.0_encoding@0.1.13\\node_modules\\libpg-query\\build\\Release\\…  
│ gyp verb cli '--module_name=queryparser',
│ gyp verb cli '--module_path=C:\\Users\\User\\projects\\nextjs-ecomm-store\\node_modules\\.pnpm\\libpg-query@15.2.0_encoding@0.1.13\\node_modules\\libpg-query\\build\\Rele…  
│ gyp verb cli '--napi_version=9',
│ gyp verb cli '--node_abi_napi=napi',
│ gyp verb cli '--napi_build_version=0',
│ gyp verb cli '--node_napi_label=node-v115'
│ gyp verb cli ]
│ gyp info using node-gyp@10.1.0
│ gyp info using node@20.12.1 | win32 | x64
│ gyp verb build type Release
│ gyp verb architecture x64
│ gyp verb node dev dir C:\Users\User\AppData\Local\node-gyp\Cache\20.12.1
│ gyp verb python C:\Python312\python.exe
│ gyp verb found first Solution file build\binding.sln
│ gyp verb using MSBuild: C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe
│ gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe
│ gyp info spawn args [
│ gyp info spawn args 'build\\binding.sln',
│ gyp info spawn args '/nologo',
│ gyp info spawn args '/p:Configuration=Release;Platform=x64'
│ gyp info spawn args ]
│ Build started 12/06/2024 19:00:41.
│ Project "C:\Users\User\projects\nextjs-ecomm-store\node_modules\.pnpm\libpg-query@15.2.0_encoding@0.1.13\node_modules\libpg-query\build\binding.sln" on node 1 (default ta…  
│ ValidateSolutionConfiguration:
│   Building solution configuration "Release|x64".
│ Project "C:\Users\User\projects\nextjs-ecomm-store\node_modules\.pnpm\libpg-query@15.2.0_encoding@0.1.13\node_modules\libpg-query\build\binding.sln" (1) is building "C:\U…  
│ PrepareForBuild:
│   Structured output is enabled. The formatting of compiler diagnostics will reflect the error hierarchy. See https://aka.ms/cpp/structured-output for more details.
│   Creating directory "C:\Users\User\projects\nextjs-ecomm-store\node_modules\.pnpm\libpg-query@15.2.0_encoding@0.1.13\node_modules\libpg-query\build\Release\".
│ InitializeBuildStatus:
│   Creating "Release\obj\nothing\nothing.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
│   Touching "Release\obj\nothing\nothing.tlog\unsuccessfulbuild".
│ ClCompile:
│   All outputs are up-to-date.
│   All outputs are up-to-date.
│ Lib:
│   C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.39.33519\bin\HostX64\x64\Lib.exe /OUT:"C:\Users\User\projects\nextjs-ecomm-store\node_mo…  
│   "Release\obj\nothing\\node-addon-api@7.1.0\node_modules\node-addon-api\nothing.obj"
│   nothing.vcxproj -> C:\Users\User\projects\nextjs-ecomm-store\node_modules\.pnpm\libpg-query@15.2.0_encoding@0.1.13\node_modules\libpg-query\build\Release\\nothing.lib     
│ FinalizeBuildStatus:
│   Deleting file "Release\obj\nothing\nothing.tlog\unsuccessfulbuild".
│   Touching "Release\obj\nothing\nothing.tlog\nothing.lastbuildstate".
│ Done Building Project "C:\Users\User\projects\nextjs-ecomm-store\node_modules\.pnpm\libpg-query@15.2.0_encoding@0.1.13\node-addon-api@7.1.0\node_modules\node-addon-api\no…  
│ Project "C:\Users\User\projects\nextjs-ecomm-store\node_modules\.pnpm\libpg-query@15.2.0_encoding@0.1.13\node_modules\libpg-query\build\binding.sln" (1) is building "C:\U…  
│ Project "C:\Users\User\projects\nextjs-ecomm-store\node_modules\.pnpm\libpg-query@15.2.0_encoding@0.1.13\node_modules\libpg-query\build\queryparser.vcxproj.metaproj" (3) …  
│ PrepareForBuild:
│   Creating directory "Release\obj\queryparser\".
│   Structured output is enabled. The formatting of compiler diagnostics will reflect the error hierarchy. See https://aka.ms/cpp/structured-output for more details.
│   Creating directory "Release\obj\queryparser\queryparser.tlog\".
│ InitializeBuildStatus:
│   Creating "Release\obj\queryparser\queryparser.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
│   Touching "Release\obj\queryparser\queryparser.tlog\unsuccessfulbuild".
│ CustomBuild:
│   prebuild_dependencies
│   Cloning into 'libpg_query'...
│   Note: switching to 'db39825bc7c1ddd45962ec6a626d740b7f8f027a'.
│
│   You are in 'detached HEAD' state. You can look around, make experimental
│   changes and commit them, and you can discard any commits you make in this
│   state without impacting any branches by switching back to a branch.
│
│   If you want to create a new branch to retain commits you create, you may
│   do so (now or later) by using -c with the switch command. Example:
│
│     git switch -c <new-branch-name>
│
│   Or undo this operation with:
│
│     git switch -
│
│   Turn off this advice by setting config variable advice.detachedHead to false
│
│   HEAD is now at db39825 Update changelog, prepare `15-4.2.4` release (#227)
│   "please ensure you are running at Windows Developer Command Prompt environments"
│
│   Microsoft (R) Program Maintenance Utility Version 14.39.33523.0
│   Copyright (C) Microsoft Corporation.  All rights reserved.
│
│ NMAKE : fatal error U1052: file 'Makefile.msvc' not found [C:\Users\User\projects\nextjs-ecomm-store\node_modules\.pnpm\libpg-query@15.2.0_encoding@0.1.13\node_modules\li…  
│   Stop.
│
│   Microsoft (R) Program Maintenance Utility Version 14.39.33523.0
│   Copyright (C) Microsoft Corporation.  All rights reserved.
│
│ NMAKE : fatal error U1052: file 'Makefile.msvc' not found [C:\Users\User\projects\nextjs-ecomm-store\node_modules\.pnpm\libpg-query@15.2.0_encoding@0.1.13\node_modules\li…  
│   Stop.
│ CUSTOMBUILD : error : 'nmake' command failed [C:\Users\User\projects\nextjs-ecomm-store\node_modules\.pnpm\libpg-query@15.2.0_encoding@0.1.13\node_modules\libpg-query\bui…  
│   File Not Found
│   "ERROR: pg_query.lib not found"
│   The system cannot find the file specified.
│           1 file(s) copied.
│ C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(254,5): error MSB8066: Custom build for '..\binding.g…  
│ Done Building Project "C:\Users\User\projects\nextjs-ecomm-store\node_modules\.pnpm\libpg-query@15.2.0_encoding@0.1.13\node_modules\libpg-query\build\queryparser.vcxproj"…  
│ Done Building Project "C:\Users\User\projects\nextjs-ecomm-store\node_modules\.pnpm\libpg-query@15.2.0_encoding@0.1.13\node_modules\libpg-query\build\queryparser.vcxproj.…  
│ Done Building Project "C:\Users\User\projects\nextjs-ecomm-store\node_modules\.pnpm\libpg-query@15.2.0_encoding@0.1.13\node_modules\libpg-query\build\binding.sln" (defaul…  
│ Build FAILED.
│ "C:\Users\User\projects\nextjs-ecomm-store\node_modules\.pnpm\libpg-query@15.2.0_encoding@0.1.13\node_modules\libpg-query\build\binding.sln" (default target) (1) ->
│ "C:\Users\User\projects\nextjs-ecomm-store\node_modules\.pnpm\libpg-query@15.2.0_encoding@0.1.13\node_modules\libpg-query\build\queryparser.vcxproj.metaproj" (default tar…  
│ "C:\Users\User\projects\nextjs-ecomm-store\node_modules\.pnpm\libpg-query@15.2.0_encoding@0.1.13\node_modules\libpg-query\build\queryparser.vcxproj" (default target) (4) …  
│ (CustomBuild target) ->
│   NMAKE : fatal error U1052: file 'Makefile.msvc' not found [C:\Users\User\projects\nextjs-ecomm-store\node_modules\.pnpm\libpg-query@15.2.0_encoding@0.1.13\node_modules\…  
│   NMAKE : fatal error U1052: file 'Makefile.msvc' not found [C:\Users\User\projects\nextjs-ecomm-store\node_modules\.pnpm\libpg-query@15.2.0_encoding@0.1.13\node_modules\…  
│   CUSTOMBUILD : error : 'nmake' command failed [C:\Users\User\projects\nextjs-ecomm-store\node_modules\.pnpm\libpg-query@15.2.0_encoding@0.1.13\node_modules\libpg-query\b…  
│   C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(254,5): error MSB8066: Custom build for '..\binding…  
│     0 Warning(s)
│     4 Error(s)
│ Time Elapsed 00:00:05.59
│ gyp ERR! build error
│ gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
│ gyp ERR! stack at ChildProcess.<anonymous> (C:\Users\User\AppData\Local\node\corepack\v1\pnpm\9.3.0\dist\node_modules\node-gyp\lib\build.js:209:23)
│ gyp ERR! stack at ChildProcess.emit (node:events:518:28)
│ gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:294:12)
│ gyp ERR! System Windows_NT 10.0.22631
│ gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\User\\AppData\\Local\\node\\corepack\\v1\\pnpm\\9.3.0\\dist\\node_modules\\node-gyp\\bin\\node-gyp.js" …  
│ gyp ERR! cwd C:\Users\User\projects\nextjs-ecomm-store\node_modules\.pnpm\libpg-query@15.2.0_encoding@0.1.13\node_modules\libpg-query
│ gyp ERR! node -v v20.12.1
│ gyp ERR! node-gyp -v v10.1.0
│ gyp ERR! not ok
│ node-pre-gyp ERR! build error
│ node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\User\AppData\Local\node\corepack\v1\pnpm\9.3.0\dist\node_modules\node-gyp\bin\…  
│ node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\User\projects\nextjs-ecomm-store\node_modules\.pnpm\@mapbox+node-pre-gyp@1.0.11_encoding@0.1.13\node_mod…  
│ node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:518:28)
│ node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1105:16)
│ node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
│ node-pre-gyp ERR! System Windows_NT 10.0.22631
│ node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\User\\projects\\nextjs-ecomm-store\\node_modules\\.pnpm\\@mapbox+node-pre-gyp@1.0.11_encoding@…  
│ node-pre-gyp ERR! cwd C:\Users\User\projects\nextjs-ecomm-store\node_modules\.pnpm\libpg-query@15.2.0_encoding@0.1.13\node_modules\libpg-query
│ node-pre-gyp ERR! node -v v20.12.1
│ node-pre-gyp ERR! node-pre-gyp -v v1.0.11
│ node-pre-gyp ERR! not ok
│ Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\User\AppData\Local\node\corepack\v1\pnpm\9.3.0\dist\node_modules\node-gyp\bin\node-gyp.js build --fallback-to…  
└─ Failed in 9s at C:\Users\User\projects\nextjs-ecomm-store\node_modules\.pnpm\libpg-query@15.2.0_encoding@0.1.13\node_modules\libpg-query
 ELIFECYCLE  Command failed with exit code 1.
node:internal/errors:984
  const err = new Error(message);
              ^

Error: Command failed: pnpm add --save-dev @ts-safeql/eslint-plugin libpg-query prettier-plugin-embed prettier-plugin-sql
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at file:///C:/Users/User/projects/nextjs-ecomm-store/node_modules/.pnpm/eslint-config-upleveled@8.2.1_@babel+core@7.24.6_@types+eslint@8.56.10_@types+node@20.12.13_@_rhlrwx2pmjlwgy5t5zzhx6eroq/node_modules/eslint-config-upleveled/bin/install.js:138:1
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
    at async loadESM (node:internal/process/esm_loader:28:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 20384,
  stdout: null,
  stderr: null
}

Node.js v20.12.1
```
Victor's Package.json from the lecture video
![a shot of Victors package JSON from the the Databases_ Improving Robustness and Catching Typos (by Victor) video - YouTube](https://github.com/upleveled/system-setup/assets/54738329/5412b534-f767-4259-acfb-fc94a8369808)

My package .json for comparison
![My package json - nextjs-ecomm-store - Visual Studio Code](https://github.com/upleveled/system-setup/assets/54738329/7e649428-6e17-4657-b522-3bd12bc4aa87)

:two: What were your expectations
That the ESLINT re-install after postgres should work

:three: Your guess of what the problem is
The Error message mentions a detatched HEAD state, and that seems to be causing the issues, but I don't understand why I would be in that state, as I haven't branched my repo and from what I read online it has to do with branching, so not sure how it connects

:four: A list of things you have tried to solve it
Looked up Git Detachted HEAD state online but I don't see how it applies to me, as I haven't branched any of my repos and as far as I can understand this normally happens when that is the case? Maybe it has something to do with where the ESLint things are stored and where I'm supposed to get it from?

**Comment by karlhorky** [comment]
Starting in [`eslint-config-upleveled@8.6.18`](https://github.com/upleveled/eslint-config-upleveled/releases/tag/v8.6.18), we are installing `libpg-query@16.2.0` for all systems:

- https://github.com/upleveled/eslint-config-upleveled/commit/d1dcb9162c5eb063f7c3a503857d92b02161cdc0

Once there are further versions published under the npm `latest` tag, we can take another look:

- https://github.com/launchql/libpg-query-node/issues/70#issuecomment-2336720161
